Enhancements and Fixes
PromptSail/prompt_sail pull request #38
Opened 2024-07-03 13:33 UTC by Bklzn

## Backend Enhancements:
- **Handling of Multi-modal Data**: Added support for Azure multi-modal data handling, including saving images from DALL-E and handling text-image combined messages.
- **SSO and Authorization**: Implemented simple custom authorization via bearer for handling OIDC and multiple fixes and enhancements in SSO configuration and error handling.
- **Transaction and Project Management**:
  - Added new endpoints and updated existing ones for better transaction management.
  - Fixed issues with transaction and project details including proxy URL configurations.
- **Performance and Optimization**:
  - Improved the functionality for streaming responses and handling of environment variables.
  - Optimized image resizing for storage and handling within the database.
- **Error Handling**: Fixed a variety of errors including a 500 error on PUT method for project configurations and login issues.

## Frontend Enhancements:
- **UI Improvements**:
  - Enhanced several pages including the login, home, and organization dashboard pages.
  - Added and updated various UI elements like submit buttons, tooltips, and loading animations.
- **Documentation and Navigation**:
  - Updated navigation structures and added detailed descriptions to the project dashboard.
  - Improved the documentation for supported models and transaction handling.
- **Error Pages and Styling Fixes**:
  - Implemented custom 404 and 500 error pages.
  - Numerous small fixes including avatar fixes in filters, interceptor adjustments, and UI style consistency.

## Configuration and Deployment:
- **Build and Deployment Enhancements**:
  - Updated project dependencies including a significant update to Langchain and integration of new libraries.
  - Rethought Docker build strategies to support environment variations.
  - Fixed issues related to the documentation build and updated the deployment cookbook.

## Documentation Enhancements and Backend Updates:
- **#37**

2024-07-03 15:39 UTC, ksopyla requested changes

2024-07-03 15:39 UTC, ksopyla commented on backend/provider_price_list.json
claude-3.5-sonet model is missing @WiolaGreen @sliwaszymon, please add

2024-07-03 15:45 UTC, ksopyla commented on backend/provider_price_list.json
and please also add groq models

2024-07-04 07:37 UTC, sliwaszymon commented on backend/provider_price_list.json
claude-3.5-sonnet and Groq models pricing added

2024-07-04 19:19 UTC, ksopyla approved these changes

2024-07-04 19:19 UTC, merged